wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693965504.828132
    t:
      1:
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.5
      5: 0.15.9
      8:
      - 5
    framework: xgboost
